In [1]:
from ultralytics import YOLO
import cv2
import argparse
import torch
import time

In [1]:
def main():
    
    
    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
    
    # 모델 로드하기
    model = YOLO(model='yolov8m-pose.pt')

    while True:

        ret, frame = cap.read()
        result = model(source = frame, conf= 0.5, show=True , verbose = False) # save = True
        print(result[0].boxes.xyxy.cpu().numpy())
        cv2.imshow("HometestCAM", frame)
        
        # if(cv2.waitKey(0) == 27): # Askii table escape == 27
        #     break 

In [3]:
main()

[[          1          50         549         480]]
[[          2          54         553         480]]
[[          2          56         555         480]]
[[          2          57         556         480]]
[[          2          57         549         480]]
[[          2          57         554         480]]
[[          2          57         555         480]]
[[          2          57         555         480]]
[[          5          56         507         480]]
[[          2          56         549         480]]
[[          4          55         526         480]]
[[          4          54         541         480]]
[[          2          55         555         480]]
[[          2          58         552         480]]
[[          2          57         553         480]]
[[          2          57         554         480]]
[[          2          57         553         480]]
[[          2          56         555         480]]
[[          2          57         555         480]
 [        129

KeyboardInterrupt: 

In [ ]:
usage: ipykernel_launcher.py [-h]
                             [--webcam-resolution WEBCAM_RESOLUTION WEBCAM_RESOLUTION]
ipykernel_launcher.py: error: unrecognized arguments: -f /Users/taeyoon/Library/Jupyter/runtime/kernel-dff0aded-321f-4f0e-b375-aefb69c3714a.json
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
/Users/taeyoon/anaconda3/envs/gj_env_jada/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3558: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)